# Setup
title: 'Jonathan Santos'
url: ""

# Settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: /:title/
future: true

# collections
collections:
  'projects':
    output: true
  'mposts':
    output: true

# Excludes
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
